import {
  DraftingCompass,
  Armchair,
  Building2,
  ConstructionIcon,
  Droplets,
  Zap,
  PaintBucket,
  Hammer,
} from "lucide-react";

// Craft definitions, icons, default specialties, and hero images per craft.
export const CRAFTS = {
  architect: {
    id: "architect",
    name: "Architect",
    tagline: "Designing spaces that inspire.",
    Icon: DraftingCompass,
    tint: "#FBE5D4",
    iconColor: "#C85F2B",
    hero: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=70",
    specialties: [
      "Residential",
      "Commercial",
      "Sustainable Design",
      "Heritage / Restoration",
      "Interior Architecture",
      "Landscape Architecture",
      "Urban Planning",
      "High-Rise",
      "Villas",
      "Hospitality",
    ],
  },
  designer: {
    id: "designer",
    name: "Designer",
    tagline: "Crafting beautiful interiors.",
    Icon: Armchair,
    tint: "#F1EBE3",
    iconColor: "#8B7E6E",
    hero: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1400&q=70",
    specialties: [
      "Interior Design",
      "Space Planning",
      "Furniture Selection",
      "Color Consulting",
      "Lighting Design",
      "3D Visualization",
      "Home Staging",
      "Modular Kitchen",
      "Wardrobes",
      "Soft Furnishings",
    ],
  },
  engineer: {
    id: "engineer",
    name: "Engineer",
    tagline: "Building with precision.",
    Icon: Building2,
    tint: "#E6EBF1",
    iconColor: "#4A6B8B",
    hero: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1400&q=70",
    specialties: [
      "Structural Engineering",
      "MEP Design",
      "Civil Engineering",
      "Site Supervision",
      "Quality Audits",
      "Project Consulting",
      "Seismic Analysis",
      "Geotechnical",
      "HVAC",
    ],
  },
  contractor: {
    id: "contractor",
    name: "Contractor",
    tagline: "Managing projects. Delivering results.",
    Icon: ConstructionIcon,
    tint: "#FDF0D8",
    iconColor: "#D4A64A",
    hero: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1400&q=70",
    wide: true,
    specialties: [
      "General Contracting",
      "Project Management",
      "Renovation",
      "New Construction",
      "Turnkey Projects",
      "Cost Estimation",
      "Design-Build",
      "Interiors Build",
      "Commercial Fit-out",
    ],
  },
  plumber: {
    id: "plumber",
    name: "Plumber",
    tagline: "Pipes, fittings & water systems.",
    Icon: Droplets,
    tint: "#E9EEF3",
    iconColor: "#5A7B93",
    hero: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=1400&q=70",
    specialties: [
      "Pipe Installation",
      "Bathroom Fitting",
      "Kitchen Plumbing",
      "Water Heater",
      "Leak Repair",
      "Drainage Systems",
      "Water Softeners",
      "Borewell",
      "Sewage Lines",
    ],
  },
  electrician: {
    id: "electrician",
    name: "Electrician",
    tagline: "Powering safe connections.",
    Icon: Zap,
    tint: "#FDF0D8",
    iconColor: "#E8A84A",
    hero: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=1400&q=70",
    specialties: [
      "House Wiring",
      "Fuse Box / DB Setup",
      "Lighting Solutions",
      "Appliance Repair",
      "Inverter & UPS",
      "Ceiling Fans",
      "CCTV & Security",
      "Generator Installation",
      "Earthing & Grounding",
      "Smart Home Integration",
      "Electrical Inspection",
    ],
  },
  painter: {
    id: "painter",
    name: "Painter",
    tagline: "Finishes that bring life.",
    Icon: PaintBucket,
    tint: "#FBE5D4",
    iconColor: "#C85F2B",
    hero: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&w=1400&q=70",
    specialties: [
      "Interior Painting",
      "Exterior Painting",
      "Texture Finishes",
      "Wallpaper Installation",
      "Waterproof Coatings",
      "Wood Polishing",
      "Metal Painting",
      "Spray Painting",
    ],
  },
  carpenter: {
    id: "carpenter",
    name: "Carpenter",
    tagline: "Precision in every detail.",
    Icon: Hammer,
    tint: "#F1EBE3",
    iconColor: "#8B5E3C",
    hero: "https://images.unsplash.com/photo-1601058272477-3cf8edbb8a51?auto=format&fit=crop&w=1400&q=70",
    specialties: [
      "Custom Furniture",
      "Cabinetry",
      "Wardrobes",
      "Modular Kitchen",
      "Doors & Windows",
      "Flooring",
      "Ceiling Work",
      "Millwork",
    ],
  },
};

export const CRAFT_GROUPS = {
  design: {
    label: "Design Professionals",
    ids: ["architect", "designer", "engineer"],
  },
  build: {
    label: "Build Professionals",
    ids: ["contractor"],
  },
  trades: {
    label: "Skilled Trades",
    ids: ["plumber", "electrician", "painter", "carpenter"],
  },
};

export const EXPERIENCE_OPTIONS = [
  "<1 Year",
  "1-2 Years",
  "3-5 Years",
  "6-8 Years",
  "8+ Years",
];

export const getCraft = (id) => CRAFTS[id] || null;
