export const PHASES = [
  {
    id:"design", name:"Design & Approval", pct:100, status:"Completed", color:"#22A36B",
    subtitle:"Architectural drawings, permits and client approvals.",
    started:"01 May 2024", end:"31 May 2024", daysUsed:30, totalDays:30,
    budget:850000, spent:850000,
    statusNote:"All approvals and drawings are complete.",
    scope:[
      {name:"Architectural Drawings", st:"done"},{name:"Structural Drawings", st:"done"},
      {name:"MEP Drawings", st:"done"},{name:"Interior Layout", st:"done"},
      {name:"Permits & NOC", st:"done"},{name:"Client Approval", st:"done"},
      {name:"Contractor Selection", st:"done"},{name:"Contract Signing", st:"done"},
    ],
    tasks:[],
    siteImg:"https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=300&q=70",
    siteCaption:"Design review meeting completed.",
    milestones:[
      {icon:"📐",name:"Drawings Approved",date:"15 May 2024",done:true},
      {icon:"📋",name:"Permits Received",date:"22 May 2024",done:true},
      {icon:"✍️",name:"Contract Signed",date:"28 May 2024",done:true},
      {icon:"🚀",name:"Site Handover",date:"01 Jun 2024",done:true},
    ],
  },
  {
    id:"sourcing", name:"Sourcing", pct:30, status:"In Progress", color:"#F59E0B",
    subtitle:"Material procurement and vendor management.",
    started:"01 Jun 2024", end:"15 Jul 2024", daysUsed:12, totalDays:45,
    budget:4000000, spent:1200000,
    statusNote:"Steel and cement ordered. Other materials pending.",
    scope:[
      {name:"Steel Procurement", st:"done"},{name:"Cement Procurement", st:"done"},
      {name:"Sand & Aggregate", st:"active"},{name:"Plumbing Fittings", st:"active"},
      {name:"Electrical Materials", st:"none"},{name:"Tiles & Flooring", st:"none"},
      {name:"Doors & Windows", st:"none"},{name:"Paint & Finishes", st:"none"},
    ],
    tasks:[
      {name:"Confirm tile vendor",cat:"Sourcing",assignee:"Rajesh Kumar",role:"Contractor",due:"25 Jun 2024",left:"3 days left",priority:"High",status:"In Progress"},
      {name:"Electrical material list approval",cat:"Sourcing",assignee:"Suresh Yadav",role:"Contractor",due:"27 Jun 2024",left:"5 days left",priority:"Medium",status:"Pending"},
    ],
    siteImg:"https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=300&q=70",
    siteCaption:"Steel bars delivered to site.",
    milestones:[
      {icon:"🔩",name:"Steel Delivery",date:"10 Jun 2024",done:true},
      {icon:"🪨",name:"Cement Stocked",date:"14 Jun 2024",done:true},
      {icon:"🚪",name:"Doors Ordered",date:"30 Jun 2024",done:false},
      {icon:"🪟",name:"Windows Delivered",date:"10 Jul 2024",done:false},
    ],
  },
  {
    id:"foundation", name:"Site & Foundation", pct:70, status:"In Progress", color:"#F59E0B",
    subtitle:"Excavation, PCC, reinforcement and foundation concrete.",
    started:"05 Jun 2024", end:"05 Jul 2024", daysUsed:21, totalDays:30,
    budget:2000000, spent:1400000,
    statusNote:"Raft slab work ongoing. Curing in progress.",
    scope:[
      {name:"Site Clearing", st:"done"},{name:"Excavation", st:"done"},
      {name:"PCC Laying", st:"done"},{name:"Reinforcement", st:"done"},
      {name:"Shuttering", st:"done"},{name:"Concrete Pouring", st:"active"},
      {name:"Curing", st:"active"},{name:"Backfilling", st:"none"},
    ],
    tasks:[
      {name:"Foundation concrete pouring",cat:"Site & Foundation",assignee:"Rajesh Kumar",role:"Contractor",due:"22 Jun 2024",left:"3 days left",priority:"High",status:"In Progress"},
      {name:"Backfilling work",cat:"Site & Foundation",assignee:"Suresh Yadav",role:"Contractor",due:"30 Jun 2024",left:"10 days left",priority:"Medium",status:"Pending"},
    ],
    siteImg:"https://images.unsplash.com/photo-1590496793929-36417d3117de?w=300&q=70",
    siteCaption:"Foundation slab curing in progress.",
    milestones:[
      {icon:"🕳️",name:"Excavation Done",date:"10 Jun 2024",done:true},
      {icon:"🏛️",name:"Plinth Beam Concrete",date:"20 Jun 2024",done:false},
      {icon:"🔧",name:"Ground Floor Columns",date:"25 Jun 2024",done:false},
      {icon:"🏗️",name:"Slab Casting",date:"05 Jul 2024",done:false},
    ],
  },
  {
    id:"structure", name:"Structure", pct:45, status:"In Progress", color:"#F59E0B",
    subtitle:"RCC structure, columns, beams, slabs and related works.",
    started:"10 Jun 2024", end:"10 Jul 2024", daysUsed:22, totalDays:30,
    budget:6500000, spent:2850000,
    statusNote:"Work is progressing as per the planned schedule.",
    scope:[
      {name:"Column Reinforcement", st:"done"},{name:"Column Shuttering", st:"done"},
      {name:"Beam Reinforcement", st:"done"},{name:"Beam Shuttering", st:"active"},
      {name:"Slab Reinforcement", st:"active"},{name:"Slab Concreting", st:"active"},
      {name:"Curing", st:"none"},{name:"Block Work (Starter)", st:"none"},
    ],
    tasks:[
      {name:"Beam Reinforcement (First Floor)",cat:"Structure",assignee:"Rajesh Kumar",role:"Contractor",due:"22 Jun 2024",left:"3 days left",priority:"High",status:"In Progress"},
      {name:"Beam Shuttering (First Floor)",cat:"Structure",assignee:"Suresh Yadav",role:"Contractor",due:"24 Jun 2024",left:"5 days left",priority:"High",status:"Pending"},
    ],
    siteImg:"https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=300&q=70",
    siteCaption:"Column shuttering work in progress.",
    milestones:[
      {icon:"🏛️",name:"Plinth Beam Concrete",date:"20 Jun 2024",done:false},
      {icon:"🔧",name:"Ground Floor Columns",date:"25 Jun 2024",done:false},
      {icon:"🏗️",name:"Slab Casting",date:"05 Jul 2024",done:false},
      {icon:"⚡",name:"Electrical Rough-in",date:"15 Jul 2024",done:false},
    ],
  },
  {
    id:"finishing", name:"Finishing", pct:0, status:"Upcoming", color:"#D1C9BF",
    subtitle:"Plastering, flooring, painting, electrical and plumbing fitting.",
    started:"—", end:"—", daysUsed:0, totalDays:60,
    budget:5000000, spent:0,
    statusNote:"This phase will begin after structural work is complete.",
    scope:[
      {name:"Plastering", st:"none"},{name:"Flooring & Tiling", st:"none"},
      {name:"Painting", st:"none"},{name:"Electrical Fitting", st:"none"},
      {name:"Plumbing Fitting", st:"none"},{name:"False Ceiling", st:"none"},
      {name:"Woodwork & Carpentry", st:"none"},{name:"Final Handover", st:"none"},
    ],
    tasks:[],
    siteImg:"https://images.unsplash.com/photo-1513694203232-719a280e022f?w=300&q=70",
    siteCaption:"Finishing phase has not started yet.",
    milestones:[
      {icon:"🪣",name:"Plastering Complete",date:"TBD",done:false},
      {icon:"🏠",name:"Flooring Done",date:"TBD",done:false},
      {icon:"🎨",name:"Painting Complete",date:"TBD",done:false},
      {icon:"🔑",name:"Final Handover",date:"TBD",done:false},
    ],
  },
];
